INSERT INTO SIKATA.MstCountries (CountryName) VALUES
                                        ('Afghanistan'),
                                        ('Albania'),
                                        ('Algeria'),
                                        ('Andorra'),
                                        ('Angola'),
                                        ('Antigua and Barbuda'),
                                        ('Argentina'),
                                        ('Armenia'),
                                        ('Australia'),
                                        ('Austria'),
                                        ('Azerbaijan'),
                                        ('Bahamas'),
                                        ('Bahrain'),
                                        ('Bangladesh'),
                                        ('Barbados'),
                                        ('Belarus'),
                                        ('Belgium'),
                                        ('Belize'),
                                        ('Benin'),
                                        ('Bhutan'),
                                        ('Bolivia'),
                                        ('Bosnia and Herzegovina'),
                                        ('Botswana'),
                                        ('Brazil'),
                                        ('Brunei'),
                                        ('Bulgaria'),
                                        ('Burkina Faso'),
                                        ('Burundi'),
                                        ('Cabo Verde'),
                                        ('Cambodia'),
                                        ('Cameroon'),
                                        ('Canada'),
                                        ('Central African Republic'),
                                        ('Chad'),
                                        ('Chile'),
                                        ('China'),
                                        ('Colombia'),
                                        ('Comoros'),
                                        ('Congo, Democratic Republic of the'),
                                        ('Congo, Republic of the'),
                                        ('Costa Rica'),
                                        ('Croatia'),
                                        ('Cuba'),
                                        ('Cyprus'),
                                        ('Czech Republic'),
                                        ('Denmark'),
                                        ('Djibouti'),
                                        ('Dominica'),
                                        ('Dominican Republic'),
                                        ('East Timor'),
                                        ('Ecuador'),
                                        ('Egypt'),
                                        ('El Salvador'),
                                        ('Equatorial Guinea'),
                                        ('Eritrea'),
                                        ('Estonia'),
                                        ('Eswatini'),
                                        ('Ethiopia'),
                                        ('Fiji'),
                                        ('Finland'),
                                        ('France'),
                                        ('Gabon'),
                                        ('Gambia'),
                                        ('Georgia'),
                                        ('Germany'),
                                        ('Ghana'),
                                        ('Greece'),
                                        ('Grenada'),
                                        ('Guatemala'),
                                        ('Guinea'),
                                        ('Guinea-Bissau'),
                                        ('Guyana'),
                                        ('Haiti'),
                                        ('Honduras'),
                                        ('Hungary'),
                                        ('Iceland'),
                                        ('India'),
                                        ('Indonesia'),
                                        ('Iran'),
                                        ('Iraq'),
                                        ('Ireland'),
                                        ('Israel'),
                                        ('Italy'),
                                        ('Jamaica'),
                                        ('Japan'),
                                        ('Jordan'),
                                        ('Kazakhstan'),
                                        ('Kenya'),
                                        ('Kiribati'),
                                        ('Korea, North'),
                                        ('Korea, South'),
                                        ('Kosovo'),
                                        ('Kuwait'),
                                        ('Kyrgyzstan'),
                                        ('Laos'),
                                        ('Latvia'),
                                        ('Lebanon'),
                                        ('Lesotho'),
                                        ('Liberia'),
                                        ('Libya'),
                                        ('Liechtenstein'),
                                        ('Lithuania'),
                                        ('Luxembourg'),
                                        ('Madagascar'),
                                        ('Malawi'),
                                        ('Malaysia'),
                                        ('Maldives'),
                                        ('Mali'),
                                        ('Malta'),
                                        ('Marshall Islands'),
                                        ('Mauritania'),
                                        ('Mauritius'),
                                        ('Mexico'),
                                        ('Micronesia'),
                                        ('Moldova'),
                                        ('Monaco'),
                                        ('Mongolia'),
                                        ('Montenegro'),
                                        ('Morocco'),
                                        ('Mozambique'),
                                        ('Myanmar'),
                                        ('Namibia'),
                                        ('Nauru'),
                                        ('Nepal'),
                                        ('Netherlands'),
                                        ('New Zealand'),
                                        ('Nicaragua'),
                                        ('Niger'),
                                        ('Nigeria'),
                                        ('North Macedonia'),
                                        ('Norway'),
                                        ('Oman'),
                                        ('Pakistan'),
                                        ('Palau'),
                                        ('Palestine'),
                                        ('Panama'),
                                        ('Papua New Guinea'),
                                        ('Paraguay'),
                                        ('Peru'),
                                        ('Philippines'),
                                        ('Poland'),
                                        ('Portugal'),
                                        ('Qatar'),
                                        ('Romania'),
                                        ('Russia'),
                                        ('Rwanda'),
                                        ('Saint Kitts and Nevis'),
                                        ('Saint Lucia'),
                                        ('Saint Vincent and the Grenadines'),
                                        ('Samoa'),
                                        ('San Marino'),
                                        ('Sao Tome and Principe'),
                                        ('Saudi Arabia'),
                                        ('Senegal'),
                                        ('Serbia'),
                                        ('Seychelles'),
                                        ('Sierra Leone'),
                                        ('Singapore'),
                                        ('Slovakia'),
                                        ('Slovenia'),
                                        ('Solomon Islands'),
                                        ('Somalia'),
                                        ('South Africa'),
                                        ('South Sudan'),
                                        ('Spain'),
                                        ('Sri Lanka'),
                                        ('Sudan'),
                                        ('Suriname'),
                                        ('Sweden'),
                                        ('Switzerland'),
                                        ('Syria'),
                                        ('Taiwan'),
                                        ('Tajikistan'),
                                        ('Tanzania'),
                                        ('Thailand'),
                                        ('Togo'),
                                        ('Tonga'),
                                        ('Trinidad and Tobago'),
                                        ('Tunisia'),
                                        ('Turkey'),
                                        ('Turkmenistan'),
                                        ('Tuvalu'),
                                        ('Uganda'),
                                        ('Ukraine'),
                                        ('United Arab Emirates'),
                                        ('United Kingdom'),
                                        ('United States'),
                                        ('Uruguay'),
                                        ('Uzbekistan'),
                                        ('Vanuatu'),
                                        ('Vatican City'),
                                        ('Venezuela'),
                                        ('Vietnam'),
                                        ('Yemen'),
                                        ('Zambia'),
                                        ('Zimbabwe');

-- Insert Data ke Tabel MstGroupMenu
INSERT INTO SIKATA.MstGroupMenu (GroupMenuName, CreatedBy)
VALUES
    ('Management', 1),
    ('Catering', 1),
    ('Buyer', 1);

-- Insert Data ke Tabel Menu
INSERT INTO SIKATA.MstMenu (Name, Host, PathMenu, GroupMenuID, CreatedBy)
VALUES
    ('Menu1', 'localhost', '/menu1', 1, 1),
    ('Menu2', 'localhost', '/menu2', 1, 1),
    ('Menu3', 'localhost', '/menu3', 2, 1),
    ('Menu4', 'localhost', '/menu4', 2, 1),
    ('Menu5', 'localhost', '/menu5', 3, 1),
    ('Menu6', 'localhost', '/menu6', 3, 1);

INSERT INTO Sikata.MstAccess (AccessName, CreatedBy)
VALUES
    ('Menu Manajemen', 1),
    ('Menu Catering', 1),
    ('Menu Buyer', 1);

INSERT INTO Sikata.MapAksesMenu(AccessID, MenuID)
VALUES
    (3, 1),
    (3, 2);